# Site wide configuration

title:            Célya Gruson-Daniel
locale:           fr_fr
url:              https://celyagd.github.io


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Célya Gruson-Daniel
  avatar: photoCGD.jpg
  bio: "Researcher, HackYourPhD & Ancre des Savoirs co-founder, #Inno3 #Open_Science #Digital_Science, #Yoga"
  email:
  disqus-shortname:
  twitter: celyagd
  facebook: c.grusondaniel
  google:
    plus:
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: celyagd
  stackoverflow:
  linkedin: celyagrusondaniel
  instagram:
  lastfm:
  tumblr: yogeekons
  pinterest:
  foursquare:
  steam:
  dribbble:
  youtube:
  soundcloud:

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
